/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppMain: typeof import('./../layout/components/AppMain.vue')['default']
    BarChart: typeof import('./../views/dashboard/components/BarChart.vue')['default']
    Breadcrumb: typeof import('./../components/Breadcrumb/index.vue')['default']
    DataStatistics: typeof import('./../views/dashboard/components/DataStatistics.vue')['default']
    Demo_1: typeof import('./../components/ECharts/Bar/Demo_1.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FunnelChart: typeof import('./../views/dashboard/components/FunnelChart.vue')['default']
    Hamburger: typeof import('./../components/Hamburger/index.vue')['default']
    IconSelect: typeof import('./../components/IconSelect/index.vue')['default']
    IEpArrowRight: typeof import('~icons/ep/arrow-right')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    ImageUpload: typeof import('./../components/Upload/ImageUpload.vue')['default']
    Line: typeof import('./../components/ECharts/Line/index.vue')['default']
    Link: typeof import('./../layout/components/Sidebar/Link.vue')['default']
    Logo: typeof import('./../layout/components/Sidebar/Logo.vue')['default']
    MultiUpload: typeof import('./../components/Upload/MultiUpload.vue')['default']
    Navbar: typeof import('./../layout/components/Navbar.vue')['default']
    Pagination: typeof import('./../components/Pagination/index.vue')['default']
    Pie: typeof import('./../components/ECharts/Pie/index.vue')['default']
    PieChart: typeof import('./../views/dashboard/components/PieChart.vue')['default']
    RadarChart: typeof import('./../views/dashboard/components/RadarChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunRecordChart: typeof import('./../views/dashboard/components/RunRecordChart.vue')['default']
    ScrollChart: typeof import('./../views/dashboard/components/ScrollChart.vue')['default']
    ScrollPane: typeof import('./../layout/components/TagsView/ScrollPane.vue')['default']
    Sidebar: typeof import('./../layout/components/Sidebar/index.vue')['default']
    SidebarItem: typeof import('./../layout/components/Sidebar/SidebarItem.vue')['default']
    SingleUpload: typeof import('./../components/Upload/SingleUpload.vue')['default']
    SpeedChart: typeof import('./../views/dashboard/components/SpeedChart.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    TagsView: typeof import('./../layout/components/TagsView/index.vue')['default']
    TextScroll: typeof import('./../components/TextScroll/TextScroll.vue')['default']
    WatchVideo: typeof import('./../components/WatchVideo/index.vue')['default']
  }
}
